# Generated by Django 4.2.1 on 2023-09-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co1', models.JSONField(default=list)),
                ('co2', models.JSONField(default=list)),
                ('co3', models.JSONField(default=list)),
                ('co4', models.JSONField(default=list)),
                ('co5', models.JSONField(default=list)),
                ('co6', models.JSONField(default=list)),
            ],
        ),
    ]
