# Generated by Django 4.2.1 on 2023-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0002_codata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=257, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
