# Generated by Django 4.2.1 on 2023-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0004_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
