# Generated by Django 4.2.1 on 2023-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0005_alter_codata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ecc', models.CharField(max_length=256)),
                ('po1', models.JSONField(default=list)),
                ('po2', models.JSONField(default=list)),
                ('po3', models.JSONField(default=list)),
                ('po4', models.JSONField(default=list)),
                ('po5', models.JSONField(default=list)),
                ('po6', models.JSONField(default=list)),
            ],
        ),
    ]
