# Generated by Django 4.2.1 on 2023-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0007_eco1'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco1',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
