# Generated by Django 4.2.1 on 2024-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0011_alter_teacher_first_name_alter_teacher_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='calcData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounded_percentage_endesem', models.IntegerField(blank=True, null=True)),
                ('rounded_percentage_assignment1', models.IntegerField(blank=True, null=True)),
                ('rounded_percentage_assignment2', models.IntegerField(blank=True, null=True)),
                ('rounded_percentage_quiz1', models.IntegerField(blank=True, null=True)),
                ('rounded_percentage_quiz2', models.IntegerField(blank=True, null=True)),
                ('rounded_percentage_quiz3', models.IntegerField(blank=True, null=True)),
                ('rounded_percentage_test', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
