# Generated by Django 4.2.1 on 2024-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0012_calcdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calcdata',
            old_name='rounded_percentage_test',
            new_name='rounded_percentage_test1',
        ),
        migrations.AddField(
            model_name='calcdata',
            name='rounded_percentage_test2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
