# Generated by Django 4.2.1 on 2024-02-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0014_calcdata_successful_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calcdata',
            old_name='successful_student',
            new_name='successful_student_ut1',
        ),
        migrations.AddField(
            model_name='calcdata',
            name='successful_student_ut2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
