# Generated by Django 4.2.1 on 2024-02-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0015_rename_successful_student_calcdata_successful_student_ut1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcdata',
            name='po1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calcdata',
            name='po2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calcdata',
            name='po3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calcdata',
            name='po4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calcdata',
            name='po5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calcdata',
            name='po6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
