# Generated by Django 4.2.1 on 2024-02-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0018_rename_successful_student_ut1_calcdata_successful_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcdata',
            name='unsuccessful_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
