# Generated by Django 4.2.1 on 2024-02-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0019_calcdata_unsuccessful_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcdata',
            name='total_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
