# Generated by Django 5.0.2 on 2024-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0025_remove_outcome_co_remove_outcome_experiment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='copodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
