# Generated by Django 5.0.2 on 2024-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0026_copodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copodata',
            name='data',
            field=models.IntegerField(max_length=100),
        ),
    ]
