# Generated by Django 5.0.2 on 2024-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0027_alter_copodata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copodata',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
