# Generated by Django 4.2.1 on 2024-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0028_alter_copodata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec01', models.FloatField(verbose_name='EC01')),
                ('ec02', models.FloatField(verbose_name='EC02')),
                ('ec03', models.FloatField(verbose_name='EC03')),
                ('ec04', models.FloatField(verbose_name='EC04')),
                ('ec05', models.FloatField(verbose_name='EC05')),
            ],
        ),
    ]
