# Generated by Django 4.2.1 on 2024-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copopapp', '0029_ecoresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoresult',
            name='ec01',
            field=models.FloatField(null=True, verbose_name='EC01'),
        ),
        migrations.AlterField(
            model_name='ecoresult',
            name='ec02',
            field=models.FloatField(null=True, verbose_name='EC02'),
        ),
        migrations.AlterField(
            model_name='ecoresult',
            name='ec03',
            field=models.FloatField(null=True, verbose_name='EC03'),
        ),
        migrations.AlterField(
            model_name='ecoresult',
            name='ec04',
            field=models.FloatField(null=True, verbose_name='EC04'),
        ),
        migrations.AlterField(
            model_name='ecoresult',
            name='ec05',
            field=models.FloatField(null=True, verbose_name='EC05'),
        ),
    ]
